language: python
sudo: false
python:
  - "2.7"
  - "3.4"
  - "3.5"
cache:
  directories:
  - .cache/pip/
  - $HOME/.cache/pip

install:
- |
  pip install django==$DJANGO_VERSION
  pip install tornado==$TORNADO_VERSION
  pip install -r requirements.txt
  python setup.py develop

script: "nosetests -w pyjade/testsuite/ -v"
env:
  matrix:
    - DJANGO_VERSION=1.6
    - DJANGO_VERSION=1.7
    - DJANGO_VERSION=1.8
    - DJANGO_VERSION=1.9
    - TORNADO_VERSION=3.2.2
    - TORNADO_VERSION=4.2
    - TORNADO_VERSION=4.3
